project:
  type: website
  output-dir: "docs"
  preview:
    port: 4200
    browser: true
    navigate: true

website:
  title: "flanker-datapipe"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: minty
    css: styles.css
    toc: true



